use std::fs;
use std::path::Path;

use rulest_indexer::cargo_meta;

const ROOT_CLAUDE_MD: &str = r#"# {{project_name}}

## Architecture

This project uses [rulest](https://github.com/anthropics/rulest) for architecture enforcement.

### MCP Oracle

Before creating new symbols, query the architecture registry:

```json
{
  "mcpServers": {
    "rulest": {
      "command": "rulest",
      "args": ["serve", "--db", ".architect/registry.db"]
    }
  }
}
```

### Routing Rules

| Concern | Crate | Notes |
|---------|-------|-------|
{{#each crates}}
| {{this.name}} | `{{this.name}}` | {{this.description}} |
{{/each}}

### Pre-flight Checklist

Before writing code:
1. Run `validate_creation` to check if the symbol already exists
2. Run `validate_dependency` to find existing types
3. Run `validate_boundary` to check ownership rules
4. Run `check_wip` to detect concurrent work
"#;

const MODULE_CLAUDE_MD: &str = r#"# {{crate_name}}

## Responsibilities

{{description}}

## Dependencies

This crate depends on: {{dependencies}}

## Ownership

This crate owns all symbols within its `src/` directory.
Do not place symbols here that belong to other crates.
"#;

const SETTINGS_JSON: &str = r#"{
  "deny": [
    "Edit **/prelude.rs without checking validate_creation first",
    "Edit **/mod.rs without checking validate_boundary first",
    "Edit **/lib.rs without checking validate_boundary first",
    "Create new public types without checking validate_dependency first"
  ]
}
"#;

#[allow(dead_code)]
const SEED_SQL: &str = r#"-- Architecture ownership rules
-- Generated by `rulest scaffold`

{{#each crates}}
INSERT INTO ownership_rules (crate_name, description, kind) VALUES ('{{this.name}}', '{{this.name}} owns its domain logic', 'must_own');
{{/each}}
"#;

pub fn run(workspace_path: &str) -> Result<(), String> {
    let workspace = Path::new(workspace_path);
    let workspace_dir = if workspace.is_file() {
        workspace
            .parent()
            .ok_or("Cannot determine workspace directory")?
    } else {
        workspace
    };

    let info = cargo_meta::extract_workspace(workspace)?;

    let project_name = workspace_dir
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "project".to_string());

    // Generate root CLAUDE.md
    let mut root_md = ROOT_CLAUDE_MD.replace("{{project_name}}", &project_name);

    // Replace the {{#each crates}} block with actual crate rows
    let crate_rows: Vec<String> = info
        .crates
        .iter()
        .map(|c| {
            format!(
                "| {} | `{}` | {} |",
                c.name,
                c.name,
                c.description.as_deref().unwrap_or("—")
            )
        })
        .collect();

    // Remove the template each block and insert actual rows
    let each_start = root_md.find("{{#each crates}}").unwrap_or(root_md.len());
    let each_end = root_md
        .find("{{/each}}")
        .map(|i| i + "{{/each}}".len())
        .unwrap_or(root_md.len());
    root_md.replace_range(each_start..each_end, &crate_rows.join("\n"));

    let claude_md_path = workspace_dir.join("CLAUDE.md");
    if !claude_md_path.exists() {
        fs::write(&claude_md_path, &root_md)
            .map_err(|e| format!("Failed to write CLAUDE.md: {}", e))?;
        println!("Created {}", claude_md_path.display());
    } else {
        println!("Skipped {} (already exists)", claude_md_path.display());
    }

    // Generate per-crate CLAUDE.md files
    for c in &info.crates {
        let crate_dir = workspace_dir.join(&c.path);
        let crate_md_path = crate_dir.join("CLAUDE.md");

        if !crate_md_path.exists() && crate_dir.exists() {
            let content = MODULE_CLAUDE_MD
                .replace("{{crate_name}}", &c.name)
                .replace(
                    "{{description}}",
                    c.description.as_deref().unwrap_or("TODO: Add description"),
                )
                .replace("{{dependencies}}", "TODO: list dependencies");

            fs::write(&crate_md_path, &content)
                .map_err(|e| format!("Failed to write {}: {}", crate_md_path.display(), e))?;
            println!("Created {}", crate_md_path.display());
        }
    }

    // Generate .claude/settings.json
    let claude_dir = workspace_dir.join(".claude");
    fs::create_dir_all(&claude_dir)
        .map_err(|e| format!("Failed to create .claude/: {}", e))?;

    let settings_path = claude_dir.join("settings.json");
    if !settings_path.exists() {
        fs::write(&settings_path, SETTINGS_JSON)
            .map_err(|e| format!("Failed to write settings.json: {}", e))?;
        println!("Created {}", settings_path.display());
    }

    // Generate seed.sql
    let architect_dir = workspace_dir.join(".architect");
    fs::create_dir_all(&architect_dir)
        .map_err(|e| format!("Failed to create .architect/: {}", e))?;

    let seed_path = architect_dir.join("seed.sql");
    if !seed_path.exists() {
        let mut seed = "-- Architecture ownership rules\n-- Generated by `rulest scaffold`\n\n"
            .to_string();
        for c in &info.crates {
            seed.push_str(&format!(
                "INSERT INTO ownership_rules (crate_name, description, kind) VALUES ('{}', '{} owns its domain logic', 'must_own');\n",
                c.name, c.name
            ));
        }
        fs::write(&seed_path, &seed)
            .map_err(|e| format!("Failed to write seed.sql: {}", e))?;
        println!("Created {}", seed_path.display());
    }

    println!("\nScaffold complete! Review the generated files and customize as needed.");

    Ok(())
}
